freeze("$(PORT_DIR)/modules")
require("aioespnow")
require("bundle-networking")
include("$(MPY_DIR)/extmod/asyncio")
require("aiorepl")
# require("dht")
# require("ds18x20")
# require("neopixel")
# require("onewire")
